### ISSUE TITLE
MMCL fails to run on Intel GPU

### ISSUE THREAD

**Issue by zanklanecek** [fangq/mmc#40]
I downloaded MMC-CL and I think that the output format for cfg.outputype 'flux', 'energy' and 'fluence' is wrong, both with cfg.gpuid=-1 and cfg.gpuid > -1. I tested the same code on older mmc builds and the result for output (output=mmclab(newcfg)) yields output.data that suits description in 'help mmclab'. However with MMC-CL build the output.data is 4x4x5 array, and the number of nodes in mesh do not change the output.data dimensions. 

Is calling mmclab function in MMC-CL build ok or should there be some function related to OpenCl?

**Comment by fangq** [comment]
hi @zanklanecek, by default, mmcl DMMC by default (i.e. `-M G` in command line, or `cfg.method='grid'` in mmclab). The DMMC algorithm is described in 

https://www.spiedigitallibrary.org/journals/journal-of-biomedical-optics/volume-24/issue-02/020503/Dual-grid-mesh-based-Monte-Carlo-algorithm-for-efficient-photon/10.1117/1.JBO.24.2.020503.full?SSO=1

briefly, it runs ray-tracing the same way as mmc (use a simplified ray-tracer), but outputs fluence in a voxelated grid. The voxel size of the grid is controlled by cfg.uinitinmm. For example, if your domain is 4x4x5 mm in physical length, and set cfg.unitninmm=0.1, this will output a volume of 41x41x51 voxels (the last layer in each direction is presumably all 0s). 

If you want to revert to the single-grid approach, you can set `cfg.method='elem'`. This is equivalent to `-M S` in the command line.

I suggest you to run the demo scripts in `mmclab/examples/demo_b1*.m` and see if you can get matching results. My student noticed that the "mmc mode" (`gpuid=-1`) on windows produced incorrect solutions, and I have made a patch and recompiled the binaries. I will email all registered users to redownload mmcl. Some of the missing dlls are also now packaged.

**Comment by zanklanecek** [comment]
Hey @fangq ,

ok setting `cfg.method='elem'` solves that problem with output.data dimensions. However the results are not comparable with old MMC. 

-Setting `gpuid=-1` yields results, that are not comparable with old MMC
-Setting `gpuid=1` yields NaN's or zeros.

I also ran your `demo_mmcl_b1_b1d.m` and results from gpu are also NaN's or zeros.

Please notify me when the patched version will be released.

Note: I ran my tests on i5-8550u. 

![image](https://user-images.githubusercontent.com/24533740/61314778-ab0f9380-a7fd-11e9-9f2e-c81265fd6311.png)

**Comment by fangq** [comment]
I am going to send an email in a second to the mailing list (sorry, forgot to add the email field in the registration form). I fixed the garbled image issue above. it was due to the incorrect RNG data type (on cgywin, long is only 32, not 64bit).

once you get the email, and redownload the package, try again, and let me know if that works for you.

**Comment by zanklanecek** [comment]
Ok I re-downloaded. Now it is working for `cfg.gpuid=-1` but still not working for gpu. I get Nan-s for `Phigpu` and everything 0 for `Phidgpu` in `demo_mmcl_b1_b1d.m`.

When running, it is using my UHD Intel 620 (from log).

![image](https://user-images.githubusercontent.com/24533740/61321197-4a875300-a80b-11e9-8a8c-3a2a2b9bf7a2.png)

**Comment by fangq** [comment]
hmm, can you test on your CPU?

**Comment by fangq** [comment]
this is what I got on my windows ryzen 1700x
![mmcl_win](https://user-images.githubusercontent.com/226913/61323712-adaec080-a7de-11e9-9e8e-7e74f7679f56.png)

**Comment by zanklanecek** [comment]
How exactly can I change from Intel GPU -> CPU?

**Comment by zanklanecek** [comment]
Ok I changed `cfg.gpuid=1` to `cfg.gpuid=2` and now it is running on CPU. It works now. I get correct results. Same as you. There is something wrong with GPU. 

My specs:
![image](https://user-images.githubusercontent.com/24533740/61326123-680dea00-a816-11e9-82b7-50fbb23c4f5b.png)

Results:
![image](https://user-images.githubusercontent.com/24533740/61326072-4f9dcf80-a816-11e9-8624-784942c70f09.png)

**Comment by fangq** [comment]
alright, I will ask my student @ShijieYan to test the Intel GPU and see if we can fix this. But for now, please find an nvidia or amd gpu, we have tested those and know those works.

**Comment by zanklanecek** [comment]
Thanks for your time and effort!

**Comment by fangq** [comment]
reopen to fix the Intel GPU issue

**Comment by ShijieYan** [comment]
Hi, @zanklanecek. Just to let you know that we have fixed this issue for Intel GPU. The fix approach is a little bit "hacky" from programming perspective, but the simulation accuracy and speed are not affected. Please feel free to download the latest package. Simply put, it is due to an error in the ray-tracer where an int32 number is incorrectly converted to float32 (-1 is cast to 1, we do not know the reason yet but we will follow up with Intel OpenCL to see if we can find a solid solution), which leads to failure of the kernel.
